cors:
  originPatterns: http://localhost:3000, http://localhost:8080, https://beatriz.com.br
file:
  uploadDir: C://UploadDir
security:
  jwt:
    token:
      secret-key: 53cr7=37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/rest_with_spring_boot
    username: root
    password: Bc33441514@
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

spring-doc:
  paths-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true