name: Continuous Integrations with GitHub Actions

on:
  push:
    branches: 
      - main 
       
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4    
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: dckr_pat_cQpmtAAx6RMxl5RH7l18YRyXoLw

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build Application Jar
      working-directory: ./StudiesAPI/
      run: mvn clean package

    - name: Docker Compose Build 
      working-directory: ./StudiesAPI/
      run: docker compose build
      
    - name: Verify Docker Images
      run: docker images  

    - name: Push to Docker Hub Container registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-beatriz:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-beatriz:${{github.run_id}}

        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-beatriz:${{github.run_id}}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-beatriz:latest

